### ISSUE TITLE
unable to install it under elgg 2.3.X

### ISSUE THREAD

**Issue by rheman** [hypeJunction/elgg-di#1]
Hi,

Thank a lot for this module. 
As you have mentioned in the README the module requires elgg 2.3.x. I have tried to install it under elgg 2.3.x and it requires php >= 7.0. So I was not able to install it because elgg 2.3.x requires 5.5 <= php < 7.0.  Moreover this module is a dependency for elgg-mentions.

So how can I install it on elgg 2.3.x

Regards,

**Comment by hypeJunction** [comment]
You might be able to install and run it under 5.5. `composer install hypejunction/elgg-di --ignore-platform-reqs`. 

Elgg 2.3 runs on PHP 7 fine.

**Comment by rheman** [comment]
Thank a lot for your answer.
I have just installed elgg-2.3.12 with php 7 and  I installed the following plugin: elgg-html, elgg-mb4 and elgg-mentions.  But when I enable your plugins the search box and the hypeWall are duplicated as you can see in the following screenshots. When I disable elgg-mentions the search box and hypeWall are not duplicated.

![Screenshot from 2019-05-24 11-41-04](https://user-images.githubusercontent.com/4598772/58322485-fec2b980-7e18-11e9-80e4-818eb74a689d.png)

![Screenshot from 2019-05-24 11-40-49](https://user-images.githubusercontent.com/4598772/58322500-05e9c780-7e19-11e9-8ccf-495ad0618584.png)


Could you help me I don't know what is going wrong.

Regards,

**Comment by hypeJunction** [comment]
There was an unreleased commit fix. I just made a new release. Give it a try.

**Comment by rheman** [comment]
Thank a release of which plugin ? elgg-html or elgg-mb4 or elgg-mentions ?

Regards,

**Comment by hypeJunction** [comment]
elgg-di

**Comment by hypeJunction** [comment]
just run `composer update`

**Comment by rheman** [comment]
Thank a lot bit i get some trouble with elgg-di. I cannot enable the elgg-di plugin dues to the following error.  (elgg 2.3.12)

`This plugin is invalid: 
`
`The required file "start.php" is missing. Location: /home/pessek/Documents/WEB/elgg2xfinal/mod/elgg-di/ `

But I ran composer update for elgg-mentions and still have the same error.

Regards,

**Comment by hypeJunction** [comment]
`elgg-di` is not a plugin. It's a dependency.

**Comment by rheman** [comment]
Yes of course. But still have the same error after composer update. I check the elgg-di version after composer update and the latest release is installed (1.1.2). But still have the same error.

**Comment by hypeJunction** [comment]
Which error?

**Comment by rheman** [comment]
Search box is displayed twice as well as hypeWall.
- HypeWall was displayed three time but now it is display twice.
- Search box is displayed twice

![Screenshot from 2019-05-24 13-26-14](https://user-images.githubusercontent.com/4598772/58327435-87e0ed00-7e27-11e9-9d04-4228fd67a1ac.png)

![Screenshot from 2019-05-24 13-25-59](https://user-images.githubusercontent.com/4598772/58327467-9929f980-7e27-11e9-865d-8a0f1e4c59d8.png)

**Comment by hypeJunction** [comment]
Did you install all plugins via composer?

**Comment by rheman** [comment]
Yes I have just went to elgg-mentions directory then ran composer update

**Comment by hypeJunction** [comment]
Why? Install the plugins with composer!!! Do not load plugin vendors for each plugin, you will end up with multiple versions of the same dependency.

Delete all plugins.

Run:

`composer require hypejunction/elgg-mentions hypejunction/elgg-mb4 hypejunction/elgg-html`

Done.

**Comment by rheman** [comment]
Thanks but i get a composer error when running the above query:

`composer require hypejunction/elgg-mentions hypejunction/elgg-mb4 hypejunction/elgg-html`

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - hypejunction/elgg-mentions 1.0.2 requires npm-asset/at.js ^1.5 -> no matching package found.
    - hypejunction/elgg-mentions 1.0.1 requires npm-asset/at.js ^1.5 -> no matching package found.
    - hypejunction/elgg-mentions 1.0.0 requires npm-asset/at.js ^1.5 -> no matching package found.
    - Installation request for hypejunction/elgg-mentions ^1.0 -> satisfiable by hypejunction/elgg-mentions[1.0.0, 1.0.1, 1.0.2].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.
```

Regards,

**Comment by hypeJunction** [comment]
You need composer asset plugin installed. I am sorry, but I don't have time to walk you through every step of the way. There is enough in the docs on how to use composer.
